# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './res/antcrawl.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AntGame(object):
    def setupUi(self, AntGame):
        AntGame.setObjectName("AntGame")
        AntGame.resize(799, 599)
        AntGame.setMinimumSize(QtCore.QSize(799, 599))
        AntGame.setMaximumSize(QtCore.QSize(799, 599))
        self.central_widget = QtWidgets.QWidget(AntGame)
        self.central_widget.setObjectName("central_widget")
        self.button_start = QtWidgets.QPushButton(self.central_widget)
        self.button_start.setGeometry(QtCore.QRect(530, 50, 200, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.button_start.setFont(font)
        self.button_start.setObjectName("button_start")
        self.label_case = QtWidgets.QLabel(self.central_widget)
        self.label_case.setGeometry(QtCore.QRect(70, 50, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.label_case.setFont(font)
        self.label_case.setObjectName("label_case")
        self.label_max = QtWidgets.QLabel(self.central_widget)
        self.label_max.setGeometry(QtCore.QRect(70, 100, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.label_max.setFont(font)
        self.label_max.setObjectName("label_max")
        self.label_min = QtWidgets.QLabel(self.central_widget)
        self.label_min.setGeometry(QtCore.QRect(70, 150, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.label_min.setFont(font)
        self.label_min.setObjectName("label_min")
        self.button_pause = QtWidgets.QPushButton(self.central_widget)
        self.button_pause.setGeometry(QtCore.QRect(530, 130, 200, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.button_pause.setFont(font)
        self.button_pause.setObjectName("button_pause")
        self.img_ant_1 = QtWidgets.QLabel(self.central_widget)
        self.img_ant_1.setGeometry(QtCore.QRect(140, 320, 81, 81))
        self.img_ant_1.setText("")
        self.img_ant_1.setPixmap(QtGui.QPixmap(":/img/ant.png"))
        self.img_ant_1.setScaledContents(True)
        self.img_ant_1.setObjectName("img_ant_1")
        self.img_stick = QtWidgets.QLabel(self.central_widget)
        self.img_stick.setGeometry(QtCore.QRect(60, 400, 681, 41))
        self.img_stick.setText("")
        self.img_stick.setPixmap(QtGui.QPixmap(":/img/stick.png"))
        self.img_stick.setScaledContents(True)
        self.img_stick.setObjectName("img_stick")
        self.img_ant_2 = QtWidgets.QLabel(self.central_widget)
        self.img_ant_2.setGeometry(QtCore.QRect(250, 320, 81, 81))
        self.img_ant_2.setText("")
        self.img_ant_2.setPixmap(QtGui.QPixmap(":/img/ant.png"))
        self.img_ant_2.setScaledContents(True)
        self.img_ant_2.setObjectName("img_ant_2")
        self.img_ant_3 = QtWidgets.QLabel(self.central_widget)
        self.img_ant_3.setGeometry(QtCore.QRect(360, 320, 81, 81))
        self.img_ant_3.setText("")
        self.img_ant_3.setPixmap(QtGui.QPixmap(":/img/ant.png"))
        self.img_ant_3.setScaledContents(True)
        self.img_ant_3.setObjectName("img_ant_3")
        self.img_ant_4 = QtWidgets.QLabel(self.central_widget)
        self.img_ant_4.setGeometry(QtCore.QRect(470, 320, 81, 81))
        self.img_ant_4.setText("")
        self.img_ant_4.setPixmap(QtGui.QPixmap(":/img/ant.png"))
        self.img_ant_4.setScaledContents(True)
        self.img_ant_4.setObjectName("img_ant_4")
        self.img_ant_5 = QtWidgets.QLabel(self.central_widget)
        self.img_ant_5.setGeometry(QtCore.QRect(580, 320, 81, 81))
        self.img_ant_5.setText("")
        self.img_ant_5.setPixmap(QtGui.QPixmap(":/img/ant.png"))
        self.img_ant_5.setScaledContents(True)
        self.img_ant_5.setObjectName("img_ant_5")
        self.label_case_num = QtWidgets.QLabel(self.central_widget)
        self.label_case_num.setGeometry(QtCore.QRect(200, 50, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.label_case_num.setFont(font)
        self.label_case_num.setObjectName("label_case_num")
        self.label_max_num = QtWidgets.QLabel(self.central_widget)
        self.label_max_num.setGeometry(QtCore.QRect(200, 100, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.label_max_num.setFont(font)
        self.label_max_num.setObjectName("label_max_num")
        self.label_min_num = QtWidgets.QLabel(self.central_widget)
        self.label_min_num.setGeometry(QtCore.QRect(200, 150, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.label_min_num.setFont(font)
        self.label_min_num.setObjectName("label_min_num")
        AntGame.setCentralWidget(self.central_widget)
        self.menubar = QtWidgets.QMenuBar(AntGame)
        self.menubar.setEnabled(False)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 799, 26))
        self.menubar.setObjectName("menubar")
        AntGame.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AntGame)
        self.statusbar.setObjectName("statusbar")
        AntGame.setStatusBar(self.statusbar)

        self.retranslateUi(AntGame)
        QtCore.QMetaObject.connectSlotsByName(AntGame)

    def retranslateUi(self, AntGame):
        _translate = QtCore.QCoreApplication.translate
        AntGame.setWindowTitle(_translate("AntGame", "蚂蚁爬杆动态演示"))
        self.button_start.setText(_translate("AntGame", "开始"))
        self.label_case.setText(_translate("AntGame", "当前游戏次数："))
        self.label_max.setText(_translate("AntGame", "当前最长用时："))
        self.label_min.setText(_translate("AntGame", "当前最短用时："))
        self.button_pause.setText(_translate("AntGame", "暂停"))
        self.label_case_num.setText(_translate("AntGame", "0"))
        self.label_max_num.setText(_translate("AntGame", "0"))
        self.label_min_num.setText(_translate("AntGame", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AntGame = QtWidgets.QMainWindow()
    ui = Ui_AntGame()
    ui.setupUi(AntGame)
    AntGame.show()
    sys.exit(app.exec_())

