# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './res/antcrawl.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AntGame(object):
    def setupUi(self, AntGame):
        AntGame.setObjectName("AntGame")
        AntGame.resize(799, 499)
        AntGame.setMinimumSize(QtCore.QSize(799, 499))
        AntGame.setMaximumSize(QtCore.QSize(799, 499))
        self.central_widget = QtWidgets.QWidget(AntGame)
        self.central_widget.setObjectName("central_widget")
        self.button_start = QtWidgets.QPushButton(self.central_widget)
        self.button_start.setGeometry(QtCore.QRect(530, 50, 200, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.button_start.setFont(font)
        self.button_start.setObjectName("button_start")
        self.label_case = QtWidgets.QLabel(self.central_widget)
        self.label_case.setGeometry(QtCore.QRect(70, 40, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.label_case.setFont(font)
        self.label_case.setObjectName("label_case")
        self.label_max = QtWidgets.QLabel(self.central_widget)
        self.label_max.setGeometry(QtCore.QRect(70, 120, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.label_max.setFont(font)
        self.label_max.setObjectName("label_max")
        self.label_min = QtWidgets.QLabel(self.central_widget)
        self.label_min.setGeometry(QtCore.QRect(70, 160, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.label_min.setFont(font)
        self.label_min.setObjectName("label_min")
        self.button_reset = QtWidgets.QPushButton(self.central_widget)
        self.button_reset.setGeometry(QtCore.QRect(530, 130, 200, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.button_reset.setFont(font)
        self.button_reset.setObjectName("button_reset")
        self.img_ant_1 = QtWidgets.QLabel(self.central_widget)
        self.img_ant_1.setGeometry(QtCore.QRect(140, 230, 81, 81))
        self.img_ant_1.setText("")
        self.img_ant_1.setPixmap(QtGui.QPixmap(":/img/ant.png"))
        self.img_ant_1.setScaledContents(True)
        self.img_ant_1.setObjectName("img_ant_1")
        self.img_stick = QtWidgets.QLabel(self.central_widget)
        self.img_stick.setGeometry(QtCore.QRect(60, 310, 681, 41))
        self.img_stick.setText("")
        self.img_stick.setPixmap(QtGui.QPixmap(":/img/stick.png"))
        self.img_stick.setScaledContents(True)
        self.img_stick.setObjectName("img_stick")
        self.img_ant_2 = QtWidgets.QLabel(self.central_widget)
        self.img_ant_2.setGeometry(QtCore.QRect(250, 230, 81, 81))
        self.img_ant_2.setText("")
        self.img_ant_2.setPixmap(QtGui.QPixmap(":/img/ant.png"))
        self.img_ant_2.setScaledContents(True)
        self.img_ant_2.setObjectName("img_ant_2")
        self.img_ant_3 = QtWidgets.QLabel(self.central_widget)
        self.img_ant_3.setGeometry(QtCore.QRect(360, 230, 81, 81))
        self.img_ant_3.setText("")
        self.img_ant_3.setPixmap(QtGui.QPixmap(":/img/ant.png"))
        self.img_ant_3.setScaledContents(True)
        self.img_ant_3.setObjectName("img_ant_3")
        self.img_ant_4 = QtWidgets.QLabel(self.central_widget)
        self.img_ant_4.setGeometry(QtCore.QRect(470, 230, 81, 81))
        self.img_ant_4.setText("")
        self.img_ant_4.setPixmap(QtGui.QPixmap(":/img/ant.png"))
        self.img_ant_4.setScaledContents(True)
        self.img_ant_4.setObjectName("img_ant_4")
        self.img_ant_5 = QtWidgets.QLabel(self.central_widget)
        self.img_ant_5.setGeometry(QtCore.QRect(580, 230, 81, 81))
        self.img_ant_5.setText("")
        self.img_ant_5.setPixmap(QtGui.QPixmap(":/img/ant.png"))
        self.img_ant_5.setScaledContents(True)
        self.img_ant_5.setObjectName("img_ant_5")
        self.label_case_num = QtWidgets.QLabel(self.central_widget)
        self.label_case_num.setGeometry(QtCore.QRect(200, 40, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.label_case_num.setFont(font)
        self.label_case_num.setObjectName("label_case_num")
        self.label_max_num = QtWidgets.QLabel(self.central_widget)
        self.label_max_num.setGeometry(QtCore.QRect(200, 120, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.label_max_num.setFont(font)
        self.label_max_num.setObjectName("label_max_num")
        self.label_min_num = QtWidgets.QLabel(self.central_widget)
        self.label_min_num.setGeometry(QtCore.QRect(200, 160, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.label_min_num.setFont(font)
        self.label_min_num.setObjectName("label_min_num")
        self.info = QtWidgets.QLabel(self.central_widget)
        self.info.setGeometry(QtCore.QRect(340, 250, 121, 31))
        self.info.setObjectName("info")
        self.label_time = QtWidgets.QLabel(self.central_widget)
        self.label_time.setGeometry(QtCore.QRect(70, 80, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.label_time.setFont(font)
        self.label_time.setObjectName("label_time")
        self.label_time_num = QtWidgets.QLabel(self.central_widget)
        self.label_time_num.setGeometry(QtCore.QRect(200, 80, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.label_time_num.setFont(font)
        self.label_time_num.setObjectName("label_time_num")
        self.label_output = QtWidgets.QLabel(self.central_widget)
        self.label_output.setGeometry(QtCore.QRect(60, 380, 681, 31))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(9)
        self.label_output.setFont(font)
        self.label_output.setObjectName("label_output")
        AntGame.setCentralWidget(self.central_widget)
        self.menubar = QtWidgets.QMenuBar(AntGame)
        self.menubar.setEnabled(False)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 799, 26))
        self.menubar.setObjectName("menubar")
        AntGame.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AntGame)
        self.statusbar.setObjectName("statusbar")
        AntGame.setStatusBar(self.statusbar)

        self.retranslateUi(AntGame)
        QtCore.QMetaObject.connectSlotsByName(AntGame)

    def retranslateUi(self, AntGame):
        _translate = QtCore.QCoreApplication.translate
        AntGame.setWindowTitle(_translate("AntGame", "蚂蚁爬杆动态演示"))
        self.button_start.setText(_translate("AntGame", "开始"))
        self.label_case.setText(_translate("AntGame", "当前实验次数："))
        self.label_max.setText(_translate("AntGame", "最长用时："))
        self.label_min.setText(_translate("AntGame", "最短用时："))
        self.button_reset.setText(_translate("AntGame", "重置"))
        self.label_case_num.setText(_translate("AntGame", "0"))
        self.label_max_num.setText(_translate("AntGame", "0 sec"))
        self.label_min_num.setText(_translate("AntGame", "0 sec"))
        self.info.setText(_translate("AntGame", "没时间弄成会动的了"))
        self.label_time.setText(_translate("AntGame", "当前使用时间："))
        self.label_time_num.setText(_translate("AntGame", "0 sec"))
        self.label_output.setText(_translate("AntGame", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AntGame = QtWidgets.QMainWindow()
    ui = Ui_AntGame()
    ui.setupUi(AntGame)
    AntGame.show()
    sys.exit(app.exec_())

